// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKckYzYqs0ZdatjX_o2qhogjfh-Cu35uE',
    appId: '1:941737921150:web:cb03a9059de2dc0fc7662f',
    messagingSenderId: '941737921150',
    projectId: 'fir-authentication-84fda',
    authDomain: 'fir-authentication-84fda.firebaseapp.com',
    databaseURL: 'https://fir-authentication-84fda-default-rtdb.firebaseio.com',
    storageBucket: 'fir-authentication-84fda.appspot.com',
    measurementId: 'G-LZH8QYZV22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGCgw0olQz2NEm_4AYC9_Upi9cEV91wCg',
    appId: '1:941737921150:android:4de165793f74e3adc7662f',
    messagingSenderId: '941737921150',
    projectId: 'fir-authentication-84fda',
    databaseURL: 'https://fir-authentication-84fda-default-rtdb.firebaseio.com',
    storageBucket: 'fir-authentication-84fda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc9y2T5RhqUyyX3PYDYFzBzWQau2b6SmE',
    appId: '1:941737921150:ios:e8f5a208e5b835e5c7662f',
    messagingSenderId: '941737921150',
    projectId: 'fir-authentication-84fda',
    databaseURL: 'https://fir-authentication-84fda-default-rtdb.firebaseio.com',
    storageBucket: 'fir-authentication-84fda.appspot.com',
    iosBundleId: 'com.example.spaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc9y2T5RhqUyyX3PYDYFzBzWQau2b6SmE',
    appId: '1:941737921150:ios:857a77325cb4d530c7662f',
    messagingSenderId: '941737921150',
    projectId: 'fir-authentication-84fda',
    databaseURL: 'https://fir-authentication-84fda-default-rtdb.firebaseio.com',
    storageBucket: 'fir-authentication-84fda.appspot.com',
    iosBundleId: 'com.example.spaceApp.RunnerTests',
  );
}
